GET http://localhost:3000/products

###
GET http://localhost:3000/products/845927dc-5787-4397-8e69-2423affd4711

###
GET http://localhost:3000/products/tv-32

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "tv 32",
    "description": "Mussum Ipsum, cacilds vidis litro abertis. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. In elementis mé pra quem é amistosis quis leo. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. Cevadis im ampola pa arma uma pindureta.",
    "image_url": "https://images.unsplash.com/photo-1570831739435-6601aa3fa4fb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218fHx8fHx8fHwxNjIzMzQ0NjY2&ixlib=rb-1.2.1&q=80&w=1080&utm_source=unsplash_source&utm_medium=referral&utm_campaign=api-credit",
    "price": 1500.99
}

###
PATCH http://localhost:3000/products/845927dc-5787-4397-8e69-2423affd4711
Content-Type: application/json

{
    "name": "tv 32 alterada",
    "price": 1500.80
}

###
DELETE http://localhost:3000/products/845927dc-5787-4397-8e69-2423affd4711

## ORDERS ####

###
GET http://localhost:3000/orders

###
GET http://localhost:3000/orders/30d08c4e-dd90-40d0-adfd-6d693abe3320


###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "credit_card": {
      "number": "1234567812345678",
      "name": "Rudolf HiOk",
      "expiration_month": 10,
      "expiration_year": 2022,
      "cvv": "123"
    },
       "items":  [
      {
          "quantity": 2,
          "product_id": "d457aff3-3705-41df-8e5b-f692f7acb1e5"
      }
   ]
}
