version: '3'

services:
  api:
    build: .
    entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
    container_name: store-api
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  db:
    build: .docker/postgres
    container_name: store-db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=store
      - PGDATA=/tmp
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: store-pgadmin
  #   tty: true
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@user.com
  #     - PGADMIN_DEFAULT_PASSWORD=123456
  #   ports:
  #     - 9000:80
  #   depends_on:
  #     - db
