apiVersion: v1
kind: ConfigMap
metadata:
  name: codebank-conf
data:
  env: |
    host=postgres-postgresql
    port=5432
    user=postgres
    password=
    dbname=codebank
    KafkaBootstrapServers=
    KafkaTransactionsTopic=payments
    security.protocol=SASL_SSL
    sasl.mechanisms="PLAIN"
    sasl.username=
    sasl.password=
