###
GET http://localhost:3002/credit-cards


###
POST http://localhost:3002/credit-cards
Content-Type: application/json

{
    "name": "Rudolf Order",
    "number": "1234123412341234"
}

## 1234567812345678

###
GET http://localhost:3002/credit-cards/1234123412341234/invoices
